name: desktop_drop
description: SA version. A plugin which allows user dragging files to your flutter desktop applications.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.0+1
homepage: https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_drop

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  cross_file: ^0.3.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  mylib01:
    git:
      url: https://github.com/krijk/mylib01.git

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DesktopDropPlugin
      linux:
        pluginClass: DesktopDropPlugin
      windows:
        pluginClass: DesktopDropPlugin
      android:
        package: one.mixin.desktop.drop
        pluginClass: DesktopDropPlugin
      web:
        pluginClass: DesktopDropWeb
        fileName: desktop_drop_web.dart